### ISSUE TITLE
Improve composer dependencies

### ISSUE THREAD

**Issue by veewee** [psalm/psalm-plugin-doctrine#68]
Hello,

I was looking into using this plugin, but notices it downloads ORM (while I am only using DBAL).
This is caused by these composer lines: 
https://github.com/weirdan/doctrine-psalm-plugin/blob/d75579d076dd69fe5120bf8a401cea06f2e04919/composer.json#L16-L17

Since you are only providing stubs, I am not sure why you need this as a dependency.
Would it be possible to declare it as a dev dependency if you require it for this package or remove it if you don't have a hard dependency on it? 

I currently solved the issue by copying the DBAL stubs locally.

**Comment by weirdan** [comment]
The motivation for declaring runtime dependencies was to make sure the plugin is not used with incompatbile versions, as that would confuse Psalm. I see two alternatives here:
1. Declare inverted range of dependencies and put that into `conflicts` section
2. Perform checks during the plugin registration and selectively enable stubs for parts that are actually present (orm, dbal, collections, etc), emit warnings if incompatible versions are detected.

The former is easier to do, the latter seems more user friendly. Thoughts?

**Comment by veewee** [comment]
Ok, that makes sense! :)

I'dd personally go for the first solution. Most developers know how to solve issues with dependency issues in composer, so it's something wa are used to.

I don't think adding warnings to psalm is a good solution, since you know it's incompatible before installation already. So why install something you can't use?

Just my 2 cents :)

**Comment by VincentLanglet** [comment]
I think adding a conflict is the best solution, like I did in this PR: https://github.com/weirdan/doctrine-psalm-plugin/pull/83

This is done this way in the phpunit plugin: https://github.com/psalm/psalm-plugin-phpunit/blob/master/composer.json#L24
